version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - pos_db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  pos_db:
    image: postgres:15
    container_name: trivia_database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./pos_db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./pos_db/seed_data.sql:/docker-entrypoint-initdb.d/02-seed_data.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  tests:
    container_name: tests
    build:
      context: .
      dockerfile: test/Dockerfile
    depends_on:
      - pos_db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app

volumes:
  postgres_data:
