version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - pos_db
    env_file:
      - .env

  pos_db:
    image: postgres:15
    container_name: trivia_database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./pos_db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./pos_db/seed_data.sql:/docker-entrypoint-initdb.d/02-seed_data.sql
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
