INSERT INTO
    Questions (description, difficult)
VALUES
    ('¿Cuál es la capital de España?', 'Easy'),
    ('¿Cuántos lados tiene un dodecágono?', 'Easy'),
    ('¿Cuál es el planeta más cercano al Sol?', 'Easy'),
    ('¿Quién pintó La Mona Lisa?', 'Easy'),
    ('¿Cuál es el océano más grande del mundo?', 'Easy'),
    ('¿Cuál es el idioma más hablado del mundo?', 'Easy'),
    ('¿En qué año comenzó la Segunda Guerra Mundial?', 'Medium'),
    ('¿Cuál es el elemento químico con símbolo Fe?', 'Medium'),
    ('¿Quién escribió "El caballero Carmelo"?', 'Medium'),
    ('¿Cuál es el nombre de la montaña más alta de América?', 'Medium'),
    ('¿En qué país se encuentra la ciudad de La Paz?', 'Medium'),
    ('¿Quién fue el presidente del Perú que falleció en un atentado en un hipódromo?', 'Hard'),
    ('¿A cuántos kilómetros de distancia se encuentra la Tierra del Sol?', 'Hard'),
    ('¿Cuándo sucedió la caída de Constantinopla?', 'Hard'),
    ('¿Cuántos años se conmemoran en las bodas de diamante?', 'Hard');


INSERT INTO
    Options (question_id, content, is_correct)
VALUES
    (1, 'Barcelona', FALSE),
    (1, 'Madrid', TRUE),
    (1, 'Lisboa', FALSE),
    (1, 'Valencia', FALSE),
    (2, '12', TRUE),
    (2, '7', FALSE),
    (2, '14', FALSE),
    (2, '4', FALSE),
    (3, 'Venus', FALSE),
    (3, 'Tierra', FALSE),
    (3, 'Mercurio', TRUE),
    (3, 'Marte', FALSE),
    (4, 'Leonardo da Vinci', TRUE),
    (4, 'Pablo Picasso', FALSE),
    (4, 'Vincent van Gogh', FALSE),
    (4, 'Miguel Ángel', FALSE),
    (5, 'Océano Atlántico', FALSE),
    (5, 'Océano Índico', FALSE),
    (5, 'Océano Pacífico', TRUE),
    (5, 'Océano Ártico', FALSE),
    (6, 'Inglés', FALSE),
    (6, 'Español', FALSE),
    (6, 'Chino mandarín', TRUE),
    (6, 'Hindi', FALSE),
    (7, '1939', TRUE),
    (7, '1914', FALSE),
    (7, '1945', FALSE),
    (7, '1935', FALSE),
    (8, 'Fósforo', FALSE),
    (8, 'Hierro', TRUE),
    (8, 'Flúor', FALSE),
    (8, 'Fermio', FALSE),
    (9, 'Mario Vargas Llosa', FALSE),
    (9, 'Abraham Valdelomar', TRUE),
    (9, 'César Vallejo', FALSE),
    (9, 'Ricardo Palma', FALSE),
    (10, 'Monte Denali', FALSE),
    (10, 'Monte Aconcagua', TRUE),
    (10, 'Huascarán', FALSE),
    (10, 'Chimborazo', FALSE),
    (11, 'Perú', FALSE),
    (11, 'Ecuador', FALSE),
    (11, 'Bolivia', TRUE),
    (11, 'Colombia', FALSE),
    (12, 'Fernando Belaúnde Terry', FALSE),
    (12, 'Luis Miguel Sánchez Cerro', TRUE),
    (12, 'Augusto B. Leguía', FALSE),
    (12, 'Manuel A. Odría', FALSE),
    (13, '150 millones de kilómetros', TRUE),
    (13, '100 millones de kilómetros', FALSE),
    (13, '200 millones de kilómetros', FALSE),
    (13, '384 mil kilómetros', FALSE),
    (14, '1453', TRUE),
    (14, '1492', FALSE),
    (14, '1204', FALSE),
    (14, '1520', FALSE),
    (15, '50 años', FALSE),
    (15, '60 años', TRUE),
    (15, '75 años', FALSE),
    (15, '100 años', FALSE);


INSERT INTO
    Game_Sessions (player_name, total_score, correct_answers, incorrect_answers, game_date)
VALUES
    ('bxc', 40, 4, 6, '2025-04-15 14:30:00'),
    ('tai', 20, 2, 8, '2025-04-15 15:00:00'),
    ('row', 30, 3, 7, '2025-04-15 17:30:00');
